FROM ollama/ollama:0.5.11

## Copy over our start.sh
WORKDIR /
COPY ./scripts/start.sh /start.sh
RUN mkdir ragfiles
COPY ./files/* /ragfiles/*


## TO-DO: remove the curl, we don't really need it (I just want it for testing)
RUN apt update && apt install
RUN apt install -y curl git wget

## Manually install golang-go, but we need to make sure we use a version higher that 18
WORKDIR /tmp
RUN wget https://go.dev/dl/go1.22.0.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.22.0.linux-amd64.tar.gz

## Update enviroment variables
RUN echo 'export GOROOT=/usr/local/go' >> ~/.profile
RUN echo 'export GOPATH=$HOME/go' >> ~/.profile
RUN echo 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH' >> ~/.profile
## Connection information to our database
RUN echo 'export DATABASE_URL=postgres:///ragdemo?host=postgres-svc' >> ~/.profile
RUN echo 'export DATABASE_URL=postgres://postgres@postgres-svc:5432/ragdemo' >> ~/.profile
RUN echo 'export PGPASSWORD=password' >> ~/.profile
## What is the connection to the ollama host
RUN echo 'export OLLAMA_HOST=localhost:11434' >> ~/.profile
RUN . ~/.profile

## TO-DO: code for the rag demo (pgdash.io)
WORKDIR /
RUN git clone https://github.com/rapidloop/ragdemo.git

## Change the entrypoint to my startup script
ENTRYPOINT ["./start.sh"]