apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    written.by: cstone
  name: postgres-pv
  namespace: jseries
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 25Gi
  storageClassName: local-storage
  local:
    path: /run/desktop/mnt/host/c/Users/c.stone/Desktop/805_projects/jseries/server/postgres/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
  volumeMode: Filesystem 