networks:
  cstone157-rag:
    driver: bridge

volumes:
  postgres_db:

services:
  # Ollama service deployment
  ollama:
    image: ollama/ollama:0.5.11
    ports:
    - 11434:11434
    container_name: ollama
    networks:
      - cstone157-rag

  postgres:
    container_name: pg_container
    #build: ./postgres
    #image: cstone157/pg_container
    image: postgres:17.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
#      - ./postgres/data:/var/lib/postgresql/data
      - postgres_db:/var/lib/postgresql/data
    networks:
      - cstone157-rag

  # Container of PGAdmin (web-based admin tool for postgres database)
  pgadmin:
    container_name: pg_admin
    #image: dpage/pgadmin4
    image: dpage/pgadmin4:9.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.org
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - pg_container
    ports:
      - "3001:80"
    networks:
      - cstone157-rag